*&---------------------------------------------------------------------*
*& Class ZCL_ORDER_RISK_NOTIFIER
*&---------------------------------------------------------------------*
CLASS zcl_order_risk_notifier DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.

    METHODS:
      send_risk_alert
        IMPORTING is_result TYPE zcl_order_risk_entity=>ty_risk_result.

  PRIVATE SECTION.

    METHODS:
      resolve_recipient
        IMPORTING iv_risk_level TYPE char10
        RETURNING VALUE(rt_recipients) TYPE STANDARD TABLE OF ad_smtpadr WITH EMPTY KEY,

      build_mail_subject
        IMPORTING is_result TYPE zcl_order_risk_entity=>ty_risk_result
        RETURNING VALUE(rv_subject) TYPE string,

      build_mail_body
        IMPORTING is_result TYPE zcl_order_risk_entity=>ty_risk_result
        RETURNING VALUE(rt_body) TYPE soli_tab,

      send_mail
        IMPORTING iv_subject    TYPE string
                  it_body       TYPE soli_tab
                  it_recipients TYPE STANDARD TABLE OF ad_smtpadr WITH EMPTY KEY.

ENDCLASS.


CLASS zcl_order_risk_notifier IMPLEMENTATION.

  METHOD send_risk_alert.

    IF is_result-risk_level <> zcl_order_risk_entity=>gc_risk_level-high
       AND is_result-risk_level <> zcl_order_risk_entity=>gc_risk_level-critical.
      RETURN.
    ENDIF.

    DATA(lt_recipients) = resolve_recipient( is_result-risk_level ).
    DATA(lv_subject)    = build_mail_subject( is_result ).
    DATA(lt_body)       = build_mail_body( is_result ).

    send_mail(
      iv_subject    = lv_subject
      it_body       = lt_body
      it_recipients = lt_recipients ).

  ENDMETHOD.

  METHOD resolve_recipient.

    " SELECT SINGLE vkgrp FROM vbak INTO @DATA(lv_vkgrp) WHERE vbeln = @iv_vbeln.
    " SELECT SINGLE ... FROM tvkgr INTO @DATA(ls_tvkgr) WHERE vkgrp = @lv_vkgrp.
    " SELECT SINGLE smtp_addr FROM adr6 INTO @DATA(lv_email)
    "   WHERE persnumber = @ls_tvkgr-persnumber_responsible.

    CASE iv_risk_level.
      WHEN zcl_order_risk_entity=>gc_risk_level-high.
        APPEND 'sales.manager@company.com' TO rt_recipients.

      WHEN zcl_order_risk_entity=>gc_risk_level-critical.
        APPEND 'sales.manager@company.com' TO rt_recipients.
        APPEND 'senior.manager@company.com' TO rt_recipients.
    ENDCASE.

  ENDMETHOD.

  METHOD build_mail_subject.

    rv_subject = |[{ is_result-risk_level }] Risk Alert - Sales Order { is_result-vbeln } - Score { is_result-total_score }|.

  ENDMETHOD.

  METHOD build_mail_body.

    DATA(lv_separator) = '--------------------------------------------------------------'.

    APPEND VALUE #( line = 'SAP Order Risk Engine - Risk Alert' ) TO rt_body.
    APPEND VALUE #( line = lv_separator ) TO rt_body.

    APPEND VALUE #( line = |Sales Order: { is_result-vbeln }| ) TO rt_body.
    APPEND VALUE #( line = |Customer   : { is_result-kunnr }| ) TO rt_body.
    APPEND VALUE #( line = |Total Score: { is_result-total_score }| ) TO rt_body.
    APPEND VALUE #( line = |Risk Level : { is_result-risk_level }| ) TO rt_body.

    APPEND VALUE #( line = lv_separator ) TO rt_body.
    APPEND VALUE #( line = 'Check | Score | Max | Status | Details' ) TO rt_body.

    LOOP AT is_result-checks ASSIGNING FIELD-SYMBOL(<ls_check>).
      DATA(lv_status) = COND char4( WHEN <ls_check>-passed = abap_true THEN 'PASS' ELSE 'FAIL' ).

      APPEND VALUE #( line = |{ <ls_check>-check_name } \| { <ls_check>-score } \| { <ls_check>-max_score } \| { lv_status } \| { <ls_check>-message }| ) TO rt_body.
    ENDLOOP.

    APPEND VALUE #( line = lv_separator ) TO rt_body.
    APPEND VALUE #( line = |Generated by SAP Order Risk Engine \| { sy-datum } { sy-uzeit }| ) TO rt_body.

  ENDMETHOD.

  METHOD send_mail.

    DATA: ls_document_data TYPE sodocchgi1,
          lt_object_content TYPE soli_tab,
          lt_receivers      TYPE STANDARD TABLE OF somlreci1.

    ls_document_data-obj_descr = iv_subject.
    ls_document_data-obj_langu = sy-langu.

    lt_object_content = it_body.

    LOOP AT it_recipients ASSIGNING FIELD-SYMBOL(<lv_recipient>).
      APPEND VALUE #( receiver = <lv_recipient> rec_type = 'U' ) TO lt_receivers.
    ENDLOOP.

    CALL FUNCTION 'SO_NEW_DOCUMENT_ATT_SEND_API1'
      EXPORTING
        document_data              = ls_document_data
        commit_work                = abap_true
      TABLES
        object_content              = lt_object_content
        receivers                   = lt_receivers
      EXCEPTIONS
        too_many_receivers          = 1
        document_not_sent           = 2
        document_type_not_exist     = 3
        operation_no_authorization  = 4
        parameter_error             = 5
        x_error                     = 6
        enqueue_error               = 7
        OTHERS                      = 8.

    IF sy-subrc <> 0.
      MESSAGE 'Risk alert email could not be sent' TYPE 'S' DISPLAY LIKE 'E'.
    ELSE.
      MESSAGE 'Risk alert email sent' TYPE 'S'.
    ENDIF.

  ENDMETHOD.

ENDCLASS.
